# -*- coding: utf-8 -*-
"""load_inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BgPX8K1FHpoAFfRkK-1fgoYNwHRtzKov
"""

import tensorflow as tf
from tensorflow.keras import Model

from google.colab import drive
drive.mount('drive', force_remount=True)

from tensorflow.keras.metrics import categorical_accuracy, top_k_categorical_accuracy

def top_3_accuracy(y_true, y_pred):
    return top_k_categorical_accuracy(y_true, y_pred, k=3)

def top_2_accuracy(y_true, y_pred):
    return top_k_categorical_accuracy(y_true, y_pred, k=2)

new_model = tf.keras.models.load_model('drive/MyDrive/Colab Notebooks/Skin Cancer/model.h5', 
                                               custom_objects={'categorical_accuracy': categorical_accuracy,'top_2_accuracy': top_2_accuracy,'top_3_accuracy': top_3_accuracy}, 
                                               compile=True)

# Check its architecture
new_model.summary()

import heapq
lesions_dict = {
    0: 'MAL - Cheratosi Attinica',
    1: 'MAL - Carcinoma Basocellulare',
    2: 'BEN - Cheratosi Benigna',
    3: 'BEN - Dermatofibroma',
    4: 'MAL - Melanoma',
    5: 'BEN - Neo Melanocitico',    
    6: 'BEN - Lesione Vascolare'
}
def risultato_analisi(classes):
    ris_list = list(classes[0])
    ris_max = ris_list.index(max(ris_list))
    print("Dall'analisi risulta un possibile {0} con valore {1}".format(lesions_dict[ris_max],max(ris_list)))
    posizioni = heapq.nlargest(3, range(len(ris_list)), key=ris_list.__getitem__)
    print("Il secondo valore più probabile è invece {0} con valore {1}".format(lesions_dict[posizioni[1]],ris_list[posizioni[1]]))

# Here's a codeblock just for fun. You should be able to upload an image here 
# and have it classified without crashing

import numpy as np
from google.colab import files
from keras.preprocessing import image

uploaded = files.upload()

for fn in uploaded.keys():
 
  # predicting images
  path = '/content/' + fn
  img = image.load_img(path, target_size=(224, 224))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)

  images = np.vstack([x])
  classes = new_model.predict(images, batch_size=10)
  risultato_analisi(classes)

